services:
  db:
    image: postgres:15-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: notusdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresqldev/data
    networks:
      - naws-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: always
    environment:
      TZ: America/Sao_Paulo
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - naws-net
    
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - naws-net
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

networks:
  naws-net:
    driver: bridge